### ISSUE TITLE
Installation failed 

### ISSUE THREAD

**Issue by Mani1124** [jsdecena/laravel-passport-mutiauth#7]
Problem 1
    - Can only install one of: laravel/framework[v5.6.12, 5.5.x-dev].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.6.12].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.6.12].
    - jsdecena/laravel-passport-multiauth v0.2.4 requires laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].
    - Installation request for jsdecena/laravel-passport-multiauth ^0.2.4 -> satisfiable by jsdecena/laravel-passport-multiauth[v0.2.4].
    - Installation request for laravel/framework (locked at v5.6.12, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.12].

My laravel version is 5.6.12

**Comment by jacinto-joao** [comment]
@jsdecena @Thoimanich Same issue here, any idea how to get it working?

![image](https://user-images.githubusercontent.com/19816874/44621745-f2222c80-a8ab-11e8-8de7-2c82927c42f3.png)

**Comment by jsdecena** [comment]
Sorry, this is >= 5.5 and yet to update it due to time constraints

**Comment by EE1234EE** [comment]
No support for Laravel >= 5.5? :( :)
